### ISSUE TITLE
When dropping an object in "build mode", both vertices should pop inside the black box

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#113]
When dropping an object in "build mode", its vertices should pop inside the black box

**Comment by samreid** [comment]
The above implementation just bumps one of the vertices inside the black box, and translates everything with it.  If a single wire is dropped outside the black box, both vertices may go to the same point.  Despite these limitations, this implementation seems very useful and may be good enough.  On hold until next published version, then @arouinfar can review and comment.

**Comment by samreid** [comment]
Please see #126 for testing.

**Comment by arouinfar** [comment]
> If a single wire is dropped outside the black box, both vertices may go to the same point.

I've noticed that both vertices <i>always</i> go to the same point, so long as both vertices were located outside of the black box. To me this doesn't cue that items must be placed <i>within</i> the black box.
![wiredot](https://cloud.githubusercontent.com/assets/8419308/15913549/db6a9e28-2d97-11e6-823b-2b54c2ec7b4f.gif)

Could the wires do this instead (or maintain their width when translating)? That way both vertices are still viewable and the wire looks like it's been moved inside the black box.
![image](https://cloud.githubusercontent.com/assets/8419308/15913675/abc5ab08-2d98-11e6-959b-e32d2f83480b.png)

It looks like the right side of the component snaps to the closest edge of the black box. If items are dropped to the left of the black box, they still appear to be outside of the black box after snapping. I think it's best if objects snap so that they are contained within the black box. 
![blackboxsnapping](https://cloud.githubusercontent.com/assets/8419308/15913699/c63200d6-2d98-11e6-8c6c-4525620bceb7.gif)

At the end of this .gif you may notice that the battery and resistor look like they may have potentially overlapped, so the resistor rotated. However, the they did not actually connect, so there may be some edge-case funniness with #125.

**Comment by samreid** [comment]
In the above commit, I iterate over all vertices in a fixed subgraph and move them all inside the black box.  It works well, but now we must tackle variable-length wires.

**Comment by samreid** [comment]
In the above solution, I applied a 2-pass approach that seems to work well for translating things as well as shrinking wires that are longer than the black box, it will need to be tested.

**Comment by samreid** [comment]
Please see #134 for testing.

**Comment by arouinfar** [comment]
Looks good @samreid! Closing.
