### ISSUE TITLE
You can create a hidden short behind a component connected to the black box vertex.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#125]
From #122, you can still create a hidden short between a component and the black box vertex since in #117 we exempted black box interface vertices from some of the rules.

We should make sure the exemptions are truly necessary.

**Comment by samreid** [comment]
Fixed above.  It is unclear whether this will conflict with other fixes from #117, so it will need to be reviewed thoroughly.

**Comment by samreid** [comment]
Please see #126 for testing.

**Comment by arouinfar** [comment]
In general, this seems to be working, but in reviewing #113, I ran into this situation.

![rotation](https://cloud.githubusercontent.com/assets/8419308/15914034/ef796bb2-2d9a-11e6-8a3b-ebe6df8a0084.gif)

The battery and resistor on the right side of the black box look like they may have potentially overlapped, so the resistor rotated. However, the the components didn't actually connect.

**Comment by arouinfar** [comment]
I'm going to be doing a bit more testing to see if I run into any other issues.

**Comment by arouinfar** [comment]
@phet-steele found another interesting case:
![vertexpushing](https://cloud.githubusercontent.com/assets/8419308/15944216/c4ca8798-2e49-11e6-93a9-5765aa165a92.gif)

After the vertex is cut, the central vertices are likely close enough to trigger the rotating behavior, but the wires don't seem to "realize" they are too close until another component is brought close.

The few issues I've observed seem to be edge cases, rather than blocking issues. I'm going to reassign to @samreid, as I'm not sure how he'll want to proceed.

**Comment by samreid** [comment]
It looks like the short circuit is resolved, I'll move the vertex movement to another issue.
