### ISSUE TITLE
Lightbulb halo loses opacity

### ISSUE THREAD

**Issue by phet-steele** [phetsims/circuit-construction-kit#127]
The halo around the lightbulb will lose its opacity when switching from Build circuit to Investigate and back. The opacity returns when moving the lightbulb:

![cckbb02](https://cloud.githubusercontent.com/assets/5863899/15836475/3ad69e40-2bf2-11e6-8ebb-ecf49f6eb812.gif)

For #126.

**Comment by samreid** [comment]
The way Scenery PhET's LightBulbNode is implemented, we cannot use opacity to fade out the light bulb image.  I've reverted that above so that neither the bulb nor brightness lines fade when switching investigate <-> build.  The correct solution to this problem is to switch to our own bulb representation, but I'm not sure whether that is needed for the study.

When this is ready for review, I'll ask @arouinfar to look at the current behavior and comment on whether we must address this for the study.

**Comment by samreid** [comment]
@arouinfar can you review the behavior in https://github.com/phetsims/circuit-construction-kit/issues/134 and comment on whether we must get the new light bulbs for the study version or whether what's implemented is sufficient?

**Comment by arouinfar** [comment]
Looks good @samreid. No need to change the light bulb artwork for the Stanford study.
