### ISSUE TITLE
Submitting/checking answer

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit#30]
Proposed in the design doc:

It seems necessary to have some sort of mechanism to reveal what is behind the black box. Programmatically checking the answer is expensive. A relatively straight-forward way to reveal the answer would be to have a “Submit” or “Reveal” button that would show a side-by-side comparison of the contents of the the black box and the student’s answer. The student could then compare the two to determine the correctness/equivalence of their response.

Here’s a wire-frame mockup of what a reveal option could look like. The mockup shows a “Submit” button, but the verbiage can be refined later. This button could be inactive until a component is attached the the black box’s interior.

![image](https://cloud.githubusercontent.com/assets/679486/14060910/c8724f90-f337-11e5-8474-31430585a005.png)

**Comment by samreid** [comment]
@arouinfar commented:

> This will work well for Interview studies, but more control over "Reveal" option is needed when scaling up to Fall 2016 classroom studies.

**Comment by samreid** [comment]
@arouinfar it wasn't clear to me from previous meetings how we ultimately decided to proceed with "show answer" UI, can you comment?

**Comment by arouinfar** [comment]
@samreid We haven't done any pixel polishing on the UI. The general layout with the side-by-side appearance is okay, but we haven't discussed how we want the contents to appear. For example, do we want to keep the border of the black box (as mocked up) to cue that you are revealing its contents? Should the solder joints be visible?  Let's discuss this more at the next design meeting.

**Comment by arouinfar** [comment]
@samreid to clarify, a pop-up window with side-by-side static images is necessary for the MVP, though we may need to do some pixel polishing.

**Comment by samreid** [comment]
I realized a shortcut that could take an order of magnitude less time to implement: the "Reveal" button could decrease the transparency of the black box.  It could work like this:

1. the user selects "build" mode and attaches at least one component to the user-created black box
2. the reveal button becomes enabled
3. while reveal is pressed, it toggles back to "investigate" and reduces the opacity of the black box
4. when reveal is released, it toggles back to build mode and restores the opacity of the black box

I'm not opposed to working toward the side-by-side, but thought I would bring this up in case we want to investigate it as a time-saving shortcut.

**Comment by arouinfar** [comment]
@samreid I'm all for time-saving measures. This seems reasonable, but I'm not entirely sure how Reveal works. Do users need to hold the button down and keep holding it down? That interaction doesn't seem very intuitive.

Or is it more like a radio button that is on/off, where "on" is step 3 of your description, and "off" is step 4? What happens if Reveal is on, and a student clicks on Build Circuit? Can they switch back to Build model, or is it disabled? I think if students have the black box "revealed" in Investigate, they should be able to switch back to Build to make comparisons between what they've built and what was hiding.  This comparison is pedagogically poweful.

**Comment by samreid** [comment]
> Do users need to hold the button down and keep holding it down? That interaction doesn't seem very intuitive.

Perhaps press-and-hold wouldn't be obvious, but when users tap and release and see the answer flicker, it may become obvious.  Having a press-and-hold button may solve issues about users trying to build a circuit while "reveal" is on, though this only helps for mouse (perhaps ok for MVP) and not for multitouch.

>  I think if students have the black box "revealed" in Investigate, they should be able to switch back to Build to make comparisons between what they've built and what was hiding. This comparison is pedagogically poweful.

I agree the users should be able to easily switch between the revealed black box and their solution (if we decide against side-by-side).

What about a "reveal" checkbox next to "Investigate" that becomes enabled after the user has built something in "build"?  Then the user would switch back and forth between "Reveal/Investigate" and "Build" using the normal radio buttons (instead of a new paradigm)?

**Comment by arouinfar** [comment]
> Perhaps press-and-hold wouldn't be obvious, but when users tap and release and see the answer flicker, it may become obvious. Having a press-and-hold button may solve issues about users trying to build a circuit while "reveal" is on

Good point @samreid. Now that I think about it more, the press-and-hold paradigm seems like a more straight-forward approach. I think it will work for Stanford's interview study this Spring, and may even scale up well for their planned classroom study this Fall. 

We will need to work more on the restrictions around when "Reveal" would become available for the Fall study. For the Spring study, the interviewer can determine whether or not a student has "sufficiently tried" and direct them to press the Reveal button. (Attaching one component in Build mode seems reasonable for the MVP since the interviewer could maintain control over this.) For the Fall, we will need to think more about how the Reveal button would become clickable.

**Comment by samreid** [comment]
Committed a reveal button above, and it is enabled when the user has connected a component to a black box interface vertex.  Putting on hold until a version is published for review.

**Comment by samreid** [comment]
Initial version is visible here, @arouinfar can you take a look?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.8/circuit-construction-kit-basics_en.html

**Comment by arouinfar** [comment]
@samreid, I worked through half of the black boxes and the reveal mechanism is feeling pretty smooth. My only request would be to kill the "What circuit is in the black box?" prompt. It seems unnecessary and I think it has the potential to be a little confusing.

**Comment by samreid** [comment]
Should we leave the "Build a circuit that behaves the same way." text or remove it too?

**Comment by arouinfar** [comment]
I think it's fine to leave the "Build a circuit..." text @samreid.
